import type { CharacterId, StoryScene } from "./story.types";

export const STORY_TITLE = "Lola y Mario: Guardianes del bosque";

export const STORY_SYNOPSIS =
  "Lola y Mario encuentran un libro misterioso que los transporta a los bosques del Ecuador. Para volver a casa deberán observar, ayudar a sus nuevos amigos y descifrar las palabras que guarda un antiguo pergamino.";

export const CHARACTERS: Record<CharacterId, {
  name: string;
  shortName: string;
  description: string;
  imageSrc: string;
  accent: "purple" | "lime" | "red" | "brown";
}> = {
  lola: {
    name: "Lola",
    shortName: "Lola",
    description: "Una pequeña científica curiosa, valiente y siempre dispuesta a descubrir cosas nuevas.",
    imageSrc: "/assets/PERSONAJES/LOLA.png",
    accent: "purple",
  },
  mario: {
    name: "Mario",
    shortName: "Mario",
    description: "Un pequeño explorador curioso, divertido y siempre listo para vivir nuevas aventuras.",
    imageSrc: "/assets/PERSONAJES/MARIO.png",
    accent: "lime",
  },
  guacamayo: {
    name: "Guacamayo verde mayor",
    shortName: "Guacamayo",
    description: "Vivo en los bosques de la Costa ecuatoriana y necesito grandes árboles para alimentarme, refugiarme y formar mi familia.",
    imageSrc: "/assets/PERSONAJES/GUACAMAYO VERDE MAYOR.png",
    accent: "red",
  },
  oso: {
    name: "Oso de anteojos",
    shortName: "Oso",
    description: "Soy tranquilo y curioso, y vivo en los bosques andinos del Ecuador.",
    imageSrc: "/assets/PERSONAJES/OSO DE ANTEOJOS.png",
    accent: "brown",
  },
};

export const STORY_SCENES = [
  {
    id: "una-tarde-especial",
    title: "Una tarde especial",
    videoSrc: "/assets/ANIMACIONES/P1.mp4",
    toneSrc: "/assets/tonos/p1.mp3",
    posterSrc: "/assets/POSTERS/P1.jpg",
    copyBlocks: [{
      text: "En una tarde, mientras el sol se escondía entre colores brillantes, una gran aventura estaba a punto de comenzar.",
      top: 2.5,
      left: 2.5,
      width: 24.6,
      align: "left",
      tone: "light",
    }],
  },
  {
    id: "la-biblioteca",
    title: "En la biblioteca",
    videoSrc: "/assets/ANIMACIONES/P2.mp4",
    toneSrc: "/assets/tonos/p2.mp3",
    posterSrc: "/assets/POSTERS/P2.jpg",
    copyBlocks: [{
      text: "Lola y Mario entraron a la biblioteca\nen busca de una nueva historia.\nRevisaron cada estante, pero ningún\nlibro logró llamar su atención.",
      top: 74,
      left: 34,
      width: 40,
      align: "center",
      tone: "light",
    }],
    interaction: { type: "characters" },
  },
  {
    id: "el-libro-misterioso",
    title: "El libro misterioso",
    videoSrc: "/assets/ANIMACIONES/P3.mp4",
    toneSrc: "/assets/tonos/p3.mp3",
    posterSrc: "/assets/POSTERS/P3.jpg",
    copyBlocks: [{
      text: "De pronto, un extraño libro\ncon misteriosos símbolos en\nsus bordes comenzó a brillar.",
      top: 20,
      left: 35.3,
      width: 29.5,
      align: "center",
      tone: "dark",
    }],
  },
  {
    id: "la-luz-magica",
    title: "Una luz mágica",
    videoSrc: "/assets/ANIMACIONES/P4.mp4",
    toneSrc: "/assets/tonos/p4.mp3",
    posterSrc: "/assets/POSTERS/P4.jpg",
    copyBlocks: [{
      text: "Un libro volando del\nestante se abrió en el\naire, liberando una luz\nmágica de sus páginas.",
      top: 7.6,
      left: 59.7,
      width: 32.1,
      align: "right",
      tone: "dark",
    }],
  },
  {
    id: "el-remolino",
    title: "Todo comenzó a girar",
    videoSrc: "/assets/ANIMACIONES/P5.mp4",
    toneSrc: "/assets/tonos/p5.mp3",
    posterSrc: "/assets/POSTERS/P5.jpg",
    copyBlocks: [{
      text: "De repente, todo\ncomenzó a dar vueltas.\nLibros, palmeras y un\nantiguo pergamino\nvolaron por el aire.",
      top: 60,
      left: 68.5,
      width: 29.1,
      align: "right",
      tone: "dark",
    }],
  },
  {
    id: "un-bosque-enorme",
    title: "¿Dónde estamos?",
    videoSrc: "/assets/ANIMACIONES/P6.mp4",
    toneSrc: "/assets/tonos/p6.mp3",
    posterSrc: "/assets/POSTERS/P6.jpg",
    copyBlocks: [{
      text: "Cuando todo se detuvo, Lola y Mario abrieron\nlos ojos con asombro. La biblioteca había\ndesaparecido y ahora estaban rodeados de\nenormes árboles y hojas verdes.",
      top: 7.8,
      left: 25,
      width: 50,
      align: "center",
      tone: "dark",
    }],
  },
  {
    id: "calmate-mario",
    title: "Primero debemos observar",
    videoSrc: "/assets/ANIMACIONES/P7.mp4",
    toneSrc: "/assets/tonos/p7.mp3",
    posterSrc: "/assets/POSTERS/P7.jpg",
    copyBlocks: [{
      text: "Mario comenzó a gritar como loco. Lola se rio al verlo y le dijo:\n—¡Cálmate, Mario! Primero debemos descubrir dónde estamos.",
      top: 8.9,
      left: 15,
      width: 70,
      align: "center",
      tone: "dark",
    }],
  },
  {
    id: "fondo-1",
    title: "La aventura continúa",
    videoSrc: "/assets/ANIMACIONES/FONDO1.mp4",
    posterSrc: "/assets/POSTERS/FONDO1.jpg",
    copyBlocks: [],
    interaction: {
      type: "choice",
      prompt: "¿Dónde crees que están Lola y Mario?",
      options: ["Costa", "Sierra", "Amazonía", "Galápagos"],
    },
  },
  {
    id: "el-pergamino",
    title: "El antiguo pergamino",
    videoSrc: "/assets/ANIMACIONES/P8.mp4",
    toneSrc: "/assets/tonos/p8.mp3",
    posterSrc: "/assets/POSTERS/P8.jpg",
    copyBlocks: [{
      text: "¡Vamos a descubrirlo! Lola tomó\nel antiguo pergamino y lo abrió.\nEn su interior descubrió un\nextraño abecedario formado por\nsímbolos.",
      top: 6.6,
      left: 4.8,
      width: 34.7,
      align: "left",
      tone: "dark",
    }],
  },
  {
    id: "mensaje-ayuda",
    title: "El primer mensaje",
    videoSrc: "/assets/ANIMACIONES/P9.mp4",
    toneSrc: "/assets/tonos/p9.mp3",
    posterSrc: "/assets/POSTERS/P9.jpg",
    copyBlocks: [{
      text: "Observa el abecedario y escribe las letras\ncorrectas en los recuadros amarillos.",
      top: 75,
      left: 50,
      width: 41.8,
      align: "center",
      tone: "dark",
    }],
    interaction: { type: "cipher", word: "COSTA" },
  },
  {
    id: "una-sombra-enorme",
    title: "Una enorme sombra",
    videoSrc: "/assets/ANIMACIONES/P10.mp4",
    toneSrc: "/assets/tonos/p10.mp3",
    posterSrc: "/assets/POSTERS/P10.jpg",
    copyBlocks: [{
      text: "¡Lo has descubierto!\nLola y Mario estaban en\nla Costa ecuatoriana.\nPero, de pronto, una\nenorme sombra pasó\nsobre ellos.",
      top: 5.3,
      left: 71.3,
      width: 26.4,
      align: "right",
      tone: "dark",
    }],
  },
  {
    id: "guacamayo-verde-mayor",
    title: "El guacamayo verde mayor",
    videoSrc: "/assets/ANIMACIONES/P11.mp4",
    toneSrc: "/assets/tonos/p11.mp3",
    posterSrc: "/assets/POSTERS/P11.jpg",
    copyBlocks: [{
      text: "Un fuerte aleteo sacudió\nlas hojas y un guacamayo\nverde mayor descendió\nfrente a ellos.\n—No tengan miedo —dijo\n—. Este bosque también\nforma parte de su hogar.",
      top: 39,
      left: 2.5,
      width: 24,
      align: "left",
      tone: "light",
    }],
    interaction: { type: "character", characterId: "guacamayo", label: "Descubre quién\nes el guacamayo\nverde mayor" },
  },
  {
    id: "el-hogar-del-guacamayo",
    title: "Un hogar entre los árboles",
    videoSrc: "/assets/ANIMACIONES/P12.mp4",
    toneSrc: "/assets/tonos/p12.mp3",
    posterSrc: "/assets/POSTERS/P12.jpg",
    copyBlocks: [
      {
        text: "El guacamayo les mostró los frutos\ndel almendro de montaña, su\nalimento favorito, y los grandes\ntroncos donde encontraba refugio.",
        top: 3.8,
        left: 3.4,
        width: 34,
        align: "left",
        tone: "light",
      },
      {
        text: "—Los árboles nos dan\nalimento, protección y un\nhogar.— explicó el\nguacamayo.”",
        top: 53.3,
        left: 75,
        width: 22.5,
        align: "right",
        tone: "light",
      },
    ],
  },
  {
    id: "el-bosque-en-silencio",
    title: "El canto del bosque se apagó",
    videoSrc: "/assets/ANIMACIONES/P13.mp4",
    toneSrc: "/assets/tonos/p13.mp3",
    posterSrc: "/assets/POSTERS/P13.jpg",
    copyBlocks: [{
      text: "De pronto, el canto del bosque se apagó.\nFrente a ellos apareció un espacio vacío.\nLleno de ramas cortadas y troncos caídos.\n—Cada vez que desaparece un árbol,\nnuestro hogar se hace más pequeño —\nexplicó el guacamayo.",
      top: 26.1,
      left: 32.7,
      width: 34.4,
      align: "center",
      tone: "light",
    }],
  },
  {
    id: "la-pequena-planta",
    title: "Proteger también es ayudar",
    videoSrc: "/assets/ANIMACIONES/P14.mp4",
    toneSrc: "/assets/tonos/p14.mp3",
    posterSrc: "/assets/POSTERS/P14.jpg",
    copyBlocks: [
      {
        text: "Lola encontró una pequeña planta\nentre las ramas. Mario retiró con\ncuidado los papeles que la cubrían\ny juntos dejaron que recibiera la\nluz del sol.",
        top: 5.3,
        left: 3.9,
        width: 29.1,
        align: "left",
        tone: "light",
      },
      {
        text: "—Proteger el bosque\ntambién significa\nprotegernos a nosotros\n—dijo el guacamayo.",
        top: 5.3,
        left: 77.1,
        width: 20.6,
        align: "right",
        tone: "light",
      },
    ],
  },
  {
    id: "insignia-costa",
    title: "La primera insignia",
    videoSrc: "/assets/ANIMACIONES/P15.mp4",
    posterSrc: "/assets/POSTERS/P15.jpg",
    copyBlocks: [{
      text: "Lola y Mario habían obtenido\nsu primera insignia. Su forma\nrepresentaba el pico del\nguacamayo verde mayor.",
      top: 9.4,
      left: 2.5,
      width: 27,
      align: "left",
      tone: "dark",
    }],
  },
  {
    id: "remolino-hacia-la-sierra",
    title: "Un nuevo destino",
    videoSrc: "/assets/ANIMACIONES/P16.mp4",
    posterSrc: "/assets/POSTERS/P16.jpg",
    copyBlocks: [{
      text: "El bosque se cubrió de\nneblina y, en un instante,\nLola y Mario aparecieron\nentre montañas y árboles\nhúmedos.",
      top: 9.4,
      left: 2.5,
      width: 28,
      align: "left",
      tone: "dark",
    }],
  },
  {
    id: "bosque-de-neblina",
    title: "Entre montañas y neblina",
    videoSrc: "/assets/ANIMACIONES/P17.mp4",
    posterSrc: "/assets/POSTERS/P17.jpg",
    copyBlocks: [],
    interaction: {
      type: "click-word",
      word: "SIERRA",
      suffix: "ECUATORIANA",
      clickGoals: [1, 2, 3, 4, 5, 6, 5],
    },
  },
  {
    id: "oso-de-anteojos",
    title: "El oso de anteojos",
    videoSrc: "/assets/ANIMACIONES/P18.mp4",
    posterSrc: "/assets/POSTERS/P18.jpg",
    copyBlocks: [{
      text: "¡Lo descubriste! Has llegado a la Sierra ecuatoriana.\nEntre la neblina apareció un oso de anteojos, llamado\nasí por las manchas claras que rodean sus ojos.",
      top: 5.9,
      left: 10,
      width: 62,
      align: "center",
      tone: "dark",
    }],
  },
] as const satisfies readonly StoryScene[];
