import type { CharacterId, StoryScene } from "./story.types";

export const STORY_TITLE = "Lola y Mario: Guardianes del bosque";

export const STORY_SYNOPSIS =
  "Lola y Mario encuentran un libro misterioso que los transporta a los bosques del Ecuador. Para volver a casa deberán observar, ayudar a sus nuevos amigos y descifrar las palabras que guarda un antiguo pergamino.";

export const CHARACTERS: Record<CharacterId, {
  name: string;
  shortName: string;
  description: string;
  imageSrc: string;
  accent: "purple" | "lime" | "red" | "brown";
}> = {
  lola: {
    name: "Lola",
    shortName: "Lola",
    description: "Una pequeña científica curiosa, valiente y siempre dispuesta a descubrir cosas nuevas.",
    imageSrc: "/assets/PERSONAJES/LOLA.png",
    accent: "purple",
  },
  mario: {
    name: "Mario",
    shortName: "Mario",
    description: "Un pequeño explorador curioso, divertido y siempre listo para vivir nuevas aventuras.",
    imageSrc: "/assets/PERSONAJES/MARIO.png",
    accent: "lime",
  },
  guacamayo: {
    name: "Guacamayo verde mayor",
    shortName: "Guacamayo",
    description: "Vivo en los bosques de la Costa ecuatoriana y necesito grandes árboles para alimentarme, refugiarme y formar mi familia.",
    imageSrc: "/assets/PERSONAJES/GUACAMAYO VERDE MAYOR.png",
    accent: "red",
  },
  oso: {
    name: "Oso de anteojos",
    shortName: "Oso",
    description: "Soy tranquilo y curioso, y vivo en los bosques andinos del Ecuador.",
    imageSrc: "/assets/PERSONAJES/OSO DE ANTEOJOS.png",
    accent: "brown",
  },
};

export const STORY_SCENES = [
  {
    id: "una-tarde-especial",
    title: "Una tarde especial",
    videoSrc: "/assets/ANIMACIONES/P1.mp4",
    posterSrc: "/assets/ESCENAS/P1.jpg",
    copyBlocks: [{
      text: "En una tarde, mientras el sol se escondía entre colores brillantes, una gran aventura estaba a punto de comenzar.",
      top: 2.5,
      left: 2.5,
      width: 24.6,
      align: "left",
      tone: "light",
    }],
  },
  {
    id: "la-biblioteca",
    title: "En la biblioteca",
    videoSrc: "/assets/ANIMACIONES/P2.mp4",
    posterSrc: "/assets/ESCENAS/P2.jpg",
    copyBlocks: [{
      text: "Lola y Mario entraron a la biblioteca\nen busca de una nueva historia.\nRevisaron cada estante, pero ningún\nlibro logró llamar su atención.",
      top: 74,
      left: 34,
      width: 40,
      align: "center",
      tone: "light",
    }],
    interaction: { type: "characters" },
  },
  {
    id: "el-libro-misterioso",
    title: "El libro misterioso",
    videoSrc: "/assets/ANIMACIONES/P3.mp4",
    posterSrc: "/assets/ESCENAS/P3.jpg",
    copyBlocks: [{
      text: "De pronto, un extraño libro\ncon misteriosos símbolos en\nsus bordes comenzó a brillar.",
      top: 20,
      left: 35.3,
      width: 29.5,
      align: "center",
      tone: "dark",
    }],
  },
  {
    id: "la-luz-magica",
    title: "Una luz mágica",
    videoSrc: "/assets/ANIMACIONES/P4.mp4",
    posterSrc: "/assets/ESCENAS/P4.jpg",
    copyBlocks: [{
      text: "Un libro volando del\nestante se abrió en el\naire, liberando una luz\nmágica de sus páginas.",
      top: 7.6,
      left: 59.7,
      width: 32.1,
      align: "right",
      tone: "dark",
    }],
  },
  {
    id: "el-remolino",
    title: "Todo comenzó a girar",
    videoSrc: "/assets/ANIMACIONES/P5.mp4",
    posterSrc: "/assets/ESCENAS/P5.jpg",
    copyBlocks: [{
      text: "De repente, todo\ncomenzó a dar vueltas.\nLibros, palmeras y un\nantiguo pergamino\nvolaron por el aire.",
      top: 60,
      left: 68.5,
      width: 29.1,
      align: "right",
      tone: "dark",
    }],
  },
  {
    id: "un-bosque-enorme",
    title: "¿Dónde estamos?",
    videoSrc: "/assets/ANIMACIONES/P6.mp4",
    posterSrc: "/assets/ESCENAS/P6.jpg",
    copyBlocks: [{
      text: "Cuando todo se detuvo, Lola y Mario abrieron los ojos con asombro. La biblioteca había desaparecido y ahora estaban rodeados de enormes árboles y hojas verdes.",
      top: 7.8,
      left: 30.9,
      width: 38.2,
      align: "center",
      tone: "dark",
    }],
  },
  {
    id: "calmate-mario",
    title: "Primero debemos observar",
    videoSrc: "/assets/ANIMACIONES/P7.mp4",
    posterSrc: "/assets/ESCENAS/P7.jpg",
    copyBlocks: [{
      text: "Mario comenzó a gritar como loco. Lola se rio al verlo y le dijo:\n—¡Cálmate, Mario! Primero debemos descubrir dónde estamos.",
      top: 8.9,
      left: 21.6,
      width: 56.8,
      align: "center",
      tone: "dark",
    }],
  },
  {
    id: "el-pergamino",
    title: "El antiguo pergamino",
    videoSrc: "/assets/ANIMACIONES/P8.mp4",
    posterSrc: "/assets/ESCENAS/P8.jpg",
    copyBlocks: [{
      text: "Lola tomó el antiguo pergamino y lo abrió. En su interior descubrió un extraño abecedario formado por símbolos.",
      top: 6.6,
      left: 4.8,
      width: 34.7,
      align: "left",
      tone: "dark",
    }],
    interaction: { type: "reveal", label: "Da click para descubrir qué guarda el pergamino" },
  },
  {
    id: "mensaje-ayuda",
    title: "El primer mensaje",
    videoSrc: "/assets/ANIMACIONES/P9.mp4",
    posterSrc: "/assets/ESCENAS/P9.jpg",
    copyBlocks: [{
      text: "Al abrirlo, descubrió un extraño abecedario formado por símbolos. Debajo de ellos aparecía un mensaje que debían descifrar.",
      top: 71.8,
      left: 52.6,
      width: 37.7,
      align: "center",
      tone: "dark",
    }],
    interaction: { type: "cipher", word: "AYUDA" },
  },
  {
    id: "una-sombra-enorme",
    title: "Una enorme sombra",
    videoSrc: "/assets/ANIMACIONES/P10.mp4",
    posterSrc: "/assets/ESCENAS/P10.jpg",
    copyBlocks: [{
      text: "De pronto, una enorme sombra cubrió a Lola y Mario. Al mirar hacia arriba, distinguieron unas grandes alas extendidas sobre ellos, pero no lograron descubrir a quién pertenecían.",
      top: 5.3,
      left: 71.3,
      width: 26.4,
      align: "right",
      tone: "dark",
    }],
  },
  {
    id: "guacamayo-verde-mayor",
    title: "El guacamayo verde mayor",
    videoSrc: "/assets/ANIMACIONES/P11.mp4",
    posterSrc: "/assets/ESCENAS/P11.jpg",
    copyBlocks: [{
      text: "Un fuerte aleteo sacudió las hojas y un guacamayo verde mayor descendió frente a ellos. Sus plumas verdes brillaban entre pequeños destellos rojos y azules.\n—No tengan miedo —dijo—. Este bosque también forma parte de su hogar.",
      top: 51.4,
      left: 4,
      width: 21.8,
      align: "left",
      tone: "light",
    }],
    interaction: { type: "character", characterId: "guacamayo", label: "Descubre quién es el guacamayo verde mayor" },
  },
  {
    id: "el-hogar-del-guacamayo",
    title: "Un hogar entre los árboles",
    videoSrc: "/assets/ANIMACIONES/P12.mp4",
    posterSrc: "/assets/ESCENAS/P12.jpg",
    copyBlocks: [
      {
        text: "El guacamayo los guió entre los árboles y les mostró los frutos que le servían de alimento y los grandes troncos donde su especie encontraba refugio.",
        top: 48.6,
        left: 71,
        width: 26.6,
        align: "right",
        tone: "light",
      },
      {
        text: "—Los árboles nos dan comida, protección y un lugar para formar nuestras familias.",
        top: 72,
        left: 72.5,
        width: 25.1,
        align: "right",
        tone: "light",
      },
    ],
  },
  {
    id: "el-bosque-en-silencio",
    title: "El canto del bosque se apagó",
    videoSrc: "/assets/ANIMACIONES/P13.mp4",
    posterSrc: "/assets/ESCENAS/P13.jpg",
    copyBlocks: [{
      text: "De pronto, el canto del bosque se apagó. Frente a ellos apareció un espacio vacío, lleno de ramas cortadas y troncos caídos.\n—Cada vez que desaparece un árbol, nuestro hogar se hace más pequeño —explicó el guacamayo.",
      top: 28.1,
      left: 32.7,
      width: 34.4,
      align: "center",
      tone: "light",
    }],
  },
  {
    id: "la-pequena-planta",
    title: "Proteger también es ayudar",
    videoSrc: "/assets/ANIMACIONES/P14.mp4",
    posterSrc: "/assets/ESCENAS/P14.jpg",
    copyBlocks: [
      {
        text: "Lola encontró una pequeña planta entre las ramas. Mario retiró con cuidado los papeles que la cubrían y juntos dejaron que recibiera la luz del sol.",
        top: 7.3,
        left: 3.9,
        width: 29.1,
        align: "left",
        tone: "light",
      },
      {
        text: "—Proteger el bosque también significa protegernos a nosotros —dijo el guacamayo.",
        top: 7.3,
        left: 77.1,
        width: 20.6,
        align: "right",
        tone: "light",
      },
    ],
    interaction: { type: "papers" },
  },
  {
    id: "insignia-costa",
    title: "La primera insignia",
    videoSrc: "/assets/ANIMACIONES/P15.mp4",
    posterSrc: "/assets/ESCENAS/P15.jpg",
    copyBlocks: [{
      text: "Al proteger la pequeña planta, Lola y Mario descubrieron que el pergamino mostraba una nueva palabra: “COSTA”, la primera insignia que habían obtenido en su aventura.",
      top: 71.8,
      left: 52.6,
      width: 37.7,
      align: "center",
      tone: "dark",
    }],
    interaction: { type: "cipher", word: "COSTA" },
  },
  {
    id: "oso-de-anteojos",
    title: "Entre montañas y neblina",
    videoSrc: "/assets/ANIMACIONES/P16.mp4",
    posterSrc: "/assets/ESCENAS/P16.jpg",
    copyBlocks: [{
      text: "El bosque se cubrió de neblina y, en un instante, Lola y Mario aparecieron entre montañas y árboles húmedos. Allí encontraron un oso con manchas claras alrededor de los ojos.\n—Cada oso de anteojos tiene marcas diferentes —les contó—. Son como nuestro propio rostro.",
      top: 6.9,
      left: 24.4,
      width: 51.2,
      align: "center",
      tone: "dark",
    }],
    interaction: { type: "bear" },
  },
  {
    id: "semillas-en-el-camino",
    title: "Semillas para nuevos bosques",
    videoSrc: "/assets/ANIMACIONES/P17.mp4",
    posterSrc: "/assets/ESCENAS/P17.jpg",
    copyBlocks: [{
      text: "Mientras caminaba buscando frutos, el oso dejaba caer semillas sobre la tierra.\n—Así ayudamos a que nuevas plantas crezcan en distintos lugares.",
      top: 6.6,
      left: 15.9,
      width: 71.2,
      align: "center",
      tone: "dark",
    }],
    interaction: { type: "ending", word: "SIERRA" },
  },
] as const satisfies readonly StoryScene[];
